### ISSUE TITLE
Countries Report

### ISSUE THREAD

**Issue by ramirezg** [18F/analytics-reporter#114]
Top countries report for:
- [ ] realtime
- [ ] 7 days
- [ ] 30 days

**Comment by JuliaWinn** [comment]
Looking at Gray's mockup in the short term I think we only need the last 90 days, unless this was something we wanted to offer users to download?
![image](https://cloud.githubusercontent.com/assets/821557/10380928/dafd1b0a-6dcb-11e5-9200-9d72bc8e0c78.png)

**Comment by konklone** [comment]
Closed in #112.
