### ISSUE TITLE
gzip is now optional for S3 buckets backed by a CloudFront distribution

### ISSUE THREAD

**Issue by konklone** [18F/analytics-reporter#131]
Amazon announced that CloudFront will now gzip responses at the CloudFront level:

![image](https://cloud.githubusercontent.com/assets/4592/11914948/c48b2e40-a65e-11e5-9b30-f10fa6b950aa.png)

It's ostensibly free of charge, though I guess there's an increase in cost in bytes transferred between CloudFront and the origin. At analytics.usa.gov, we have caching turned to 0 seconds to facilitate immediate deploys for a site which doesn't get a ton of traffic, so we may actually see this increase in cost more than most users in our situation. However, it should still be very small given the amount of traffic we get there.

The small S3 integration code we have should probably let gzipping be optional (and opt-in), to let users take advantage of this who wish to.

**Comment by levinmr** [comment]
done
