### ISSUE TITLE
Provide more "Top Downloads" than just yesterday's

### ISSUE THREAD

**Issue by rebeccawilliams** [18F/analytics-reporter#136]
It looks like in the recent update "Top downloads over 7 days" was changed to "Top downloads yesterday." This provides more insight into yesterday, but requires users to come back daily if they're interested in popular downloads over time. Also, the righthand side of the dashboard has inconsistent time ranges on display and available for download and is confusing. Why not provide Top Downloads in the 7 and 30 day range as well? Why not provide all downloadable datasets in (the largest of those) 30 day snapshots?

It would be great to see Top Downloads displayed at 7 and 30 days as well and to offer Top Downloads over 30 days as downloadable data.

**Comment by laurenancona** [comment]
@rebeccawilliams That `7 day` report is actually still there, hanging out in the config file & pushing data to s3: https://analytics.usa.gov/data/top-downloads-7-days.csv . Looks like it just got bumped from the UI.

**Comment by levinmr** [comment]
done
