### ISSUE TITLE
Getting no output or errors on install in Ubuntu

### ISSUE THREAD

**Issue by hamptonmf** [18F/analytics-reporter#141]
Hi,

I gave up on the Windows install because I couldn't get the env variables to set correctly, so I did an install on an Ubuntu VM. There were no errors on the install, but I also can't get any output when I do the test "./bin/analytics --only users." Could I get some help on this?

Thanks,
Michael

**Comment by konklone** [comment]
No output at all? When I run this, I get:

```
$ ./bin/analytics --only users
Report not defined.
```

Does running `./bin/analytics --only devices` get you anything? That is a defined report out of the box.

**Comment by konklone** [comment]
Also, did it look like everything installed correctly during `npm install`?

**Comment by hamptonmf** [comment]
I get nothing when I run ./bin/analytics --only users. No output at all, just a new command line in the terminal. Yes, everything seemed to install ok during npm install. I got some warnings about versions of node (0.10.25 rather than 0.10.40).

**Comment by konklone** [comment]
I'm honestly not sure what code path would arrive at there being no output. Can you run `npm test` and get any output from that?

Another suggestion, which I understand is a bit burdensome, would be to add some console.log statements to [the bin/analytics script](https://github.com/18F/analytics-reporter/blob/master/bin/analytics) and see what you can get it to say and where it seems to cut off? 

It's very async, so most of the work is done inside the [async.eachSeries callback](https://github.com/18F/analytics-reporter/blob/master/bin/analytics#L128-L136). (This gets executed after the `run()` function gets called at the bottom.)

**Comment by hamptonmf** [comment]
I'll give npm test a go (running updates again right now). I've got a meeting in 15 minutes, so it may be a while before I can get back on here.

Thanks for the help!

**Comment by hamptonmf** [comment]
I get 
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN for further explanations, please read /usr/share/doc/nodejs/README.Debian
npm ERR! not ok code 0

So I'm guessing that the warnings during install weren't so much warnings as errors.

**Comment by konklone** [comment]
Interesting...you may want to install a newer version of Node on the VM then, either by downloading a binary from nodejs.org, or by using [`nvm`](https://github.com/creationix/nvm) to install and manage active Node versions in userspace. IIRC, we use `nvm` in production for this purpose.

**Comment by hamptonmf** [comment]
ok, that helped...

Now I get ERROR AFTER QUERYING: Error: No key or keyFile set. But, I'm pretty sure I have a keyFile set.

export ANALYTICS_REPORT_EMAIL="DORWebmaster@revenue.wi.gov"
export ANALYTICS_REPORT_IDS="ga:51886655"
export ANALYTICS_KEY_PATH="/home/michael/Documents/client_secret_914014050945-3uv2utdctpdi84hsvchcg1rv6nfgl5fa.apps.googleusercontent.com.json"

What am I missing?

**Comment by konklone** [comment]
@hamptonmf If you want to hop in 18F's public Slack (#devops-public would be the best), then maybe it's worth some more realtime interaction: https://chat.18f.gov/

(I'll be in and out of meetings today, though.)

**Comment by hamptonmf** [comment]
LOL, that would be great but we block all chat here at the Wisconsin Department of Revenue. I just tried and it triggered our security program.

**Comment by wslack** [comment]
@hamptonmf Oh dear! (sidenote: former Madison resident here, do you work in the building on Rimrock?)

**Comment by hamptonmf** [comment]
Yep. I'm the "webmaster" for the DOR.

**Comment by hamptonmf** [comment]
It's working now. I had a bad key file. Thanks for everything!

**Comment by konklone** [comment]
Yay!
