### ISSUE TITLE
In readme, link to 18F/analytics.usa.gov

### ISSUE THREAD

**Issue by brittag** [18F/analytics-reporter#150]
For a person who lands on this repository readme and is curious about how to use this tool, it'd be nice to expand the intro ("A lightweight system for publishing analytics data from Google Analytics profiles.") to link to [18F/analytics.usa.gov](https://github.com/18F/analytics.usa.gov) and explain that it's an example frontend that uses this code (hopefully with more precise and detailed language than that). It'd be nice to also note other interesting example uses of this code in the wild, if people have used it for things other than analytics.usa.gov-style websites.

**Comment by konklone** [comment]
> it'd be nice to expand the intro ("A lightweight system for publishing analytics data from Google Analytics profiles.") to link to 18F/analytics.usa.gov and explain that it's an example frontend that uses this code (hopefully with more precise and detailed language than that). 

PR welcome!

>  It'd be nice to also note other interesting example uses of this code in the wild, if people have used it for things other than analytics.usa.gov-style websites.

I personally know of two examples, an internal State Department project and an internal Medium.com project. Unfortunately, neither can be linked to. I'm not sure we'll always know about other uses. :(

**Comment by gbinal** [comment]
This is done.  https://github.com/18F/analytics-reporter/commit/6e328d4bdd57342293bbb2cba3b25518b7433228
