### ISSUE TITLE
Error on installing from npm - can only install on a Mac?

### ISSUE THREAD

**Issue by morinoalaria** [18F/analytics-reporter#151]
I get this error when I try to install on my Windows machine:

50 error notsup Unsupported
50 error notsup Not compatible with your operating system or architecture: analytics-reporter@1.1.1
50 error notsup Valid OS:    !win32
50 error notsup Valid Arch:  any
50 error notsup Actual OS:   win32
50 error notsup Actual Arch: x64
51 error System Windows_NT 6.1.7601
52 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "analytics-reporter"

Tried installing another package just to make sure I have node and all, but it worked ok.

Can I not install this on a Windows machine?

**Comment by thekaveman** [comment]
Probably the same issue as #138.

The NPM package wasn't updated with the fix, however @konklone indicates that the `master` branch was updated.

**Comment by konklone** [comment]
I just pushed the latest `master` to npm as version `1.1.2`. Please re-open if you still see this issue with `1.1.2`.
