### ISSUE TITLE
Explicitly call out Google API version

### ISSUE THREAD

**Issue by thekaveman** [18F/analytics-reporter#158]
This was alluded to in [a comment on another issue](https://github.com/18F/analytics-reporter/pull/91#issuecomment-87730289), and based on the query parameters it seems we target [Core Reporting API Version 3.0](https://developers.google.com/analytics/devguides/reporting/core/v3/).

I'm wondering if it makes sense to explicitly call this out (e.g. in the README) just so there is no confusion?

**Comment by gbinal** [comment]
Great call.  Done.
