### ISSUE TITLE
Evaluate v4 of the Core Reporting API

### ISSUE THREAD

**Issue by konklone** [18F/analytics-reporter#160]
There's been an update:
- https://developers.google.com/analytics/devguides/reporting/core/v4/
- Migration guide: https://developers.google.com/analytics/devguides/reporting/core/v4/

The [key features](https://developers.google.com/analytics/devguides/reporting/core/v4/#features) are:
- Metric expressions
  
  > The API allows you to request not only built-in metrics but also combination of metrics expressed in mathematical operations. For example, you can use the expression ga:goal1completions/ga:sessions to request the goal completions per number of sessions.
- Multiple date ranges
  
  > The API allows you in a single request to get data in two date ranges.
- Cohorts and Lifetime value
  
  > The API has a rich vocabulary to request Cohort and Lifetime value reports.
- Multiple segments
  
  > The API enables you to get multiple segments in a single request.

**Comment by thekaveman** [comment]
A key difference that will affect existing reports is the `sort` parameter, which has [changed to `orderBys`](https://developers.google.com/analytics/devguides/reporting/core/v4/migration#sorting)

**Comment by levinmr** [comment]
done
