### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by jmolayem** [18F/analytics-reporter#169]
Anyone else getting this error: "The bucket you are attempting to access must be addressed using the specified endpoint". Do we need use us-east-1?

**Comment by konklone** [comment]
Googling around, [found these Amazon docs](http://docs.aws.amazon.com/redshift/latest/dg/s3serviceexception-error.html):

> The Amazon S3 bucket specified in the COPY command must be in the same region as the cluster.
> ...
> You can create an Amazon S3 bucket in a specific region either by selecting the region when you create the bucket by using the Amazon S3 Management Console, or by specifying an endpoint when you create the bucket using the Amazon S3 API or CLI.

**Comment by jmolayem** [comment]
Yeah, found that helpful. It turns out I actually really needed to use us-east-1 for some reason. The error went away when I changed the bucket and .env to us-east-1.

**Comment by jmolayem** [comment]
I'm working on getting this up and running for the City of LA (http://analyticsdash-jm.s3.amazonaws.com/index.html). Quick separate question: do you guys use a separate service for chron (i.e. on digital ocean, etc) or is that built in already on the analytics reporter? Not sure how the data constantly gets pushed to the static jekyll page.

**Comment by konklone** [comment]
Yeah, we have an EC2 instance in AWS that runs analytics-reporter on a cronjob. It's authorized to publish the JSON files to an S3 bucket, which makes them available at public URLs.
