### ISSUE TITLE
How to get "All Participating Websites" data

### ISSUE THREAD

**Issue by jmolayem** [18F/analytics-reporter#171]
To get the statistics for all participating websites, I noticed 18F created a dap-1.env file. 

`source $HOME/envs/projects/dap-1.env
$HOME/analytics-reporter/bin/analytics --publish --frequency=realtime --slim --verbose
$HOME/analytics-reporter/bin/analytics --publish --only=all-pages-realtime --slim --verbose --csv`

Does dap-1.env reference a separate Google Analytics account that has put the GA code in all of the sites? Is there a way to show "all participating sites" by aggregating the individual API responses from each agency?

**Comment by tdlowden** [comment]
hi @jmolayem, I think I'll need some help from @konklone to answer the more technical part of this, but to speak to the accounts: all of the data on analytics.usa.gov is pulled from one account, albeit separate views. Each site contains the same DAP GA code and points to one account number. The agency pages are linked to specific agency views in the GA account that are filtered for that agency's domains. The "All Participating Websites" info is from a view with no domain-specific filters.  So based on our structure, we don't need to aggregate API responses from various accounts.

That said, I'm sure you could do something like that; unfortunately, I'm not of much use in describing the best way to do so.

**Comment by konklone** [comment]
@jmolayem No, `dap-1.env` and `dap-2.env` just reference different API keys to access Google Analytics data, to split our requests across applications to keep us below API key quotas. 

But you can get a list of all participating sites from the CSV we re-generate each night:

https://analytics.usa.gov/data/live/sites.csv

I hope this helps!
