### ISSUE TITLE
Move keys from .env and JSON files into the environment

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics-reporter#183]
Currently, the reporter requires files named `dap-1.env`, `dap-2.env`, and some JSON files with keys to be present in order to work. As part of moving to GovCloud, we should remove the relevant parts of these files into a cloud.gov user provided service.

Since we have 2 accounts for fetching analytics data, this will likely involve inventing a way to switch out the keys so we don't max out the GA API rate limit.

**Comment by levinmr** [comment]
done
