### ISSUE TITLE
Reports do not include total number of visitors

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics-reporter#189]
The reports the analytics reporter is generating count the total number of visits to a domain, but they do not provide the total number of visitors.

Here is the JSON generated for all domains over 30 days: https://analytics.usa.gov/data/live/all-domains-30-days.json

Scroll to the `totals` prop and you'll see that it includes `visits`, but not `visitors`.

The code to calculate the number of visitors is [here](https://github.com/18F/analytics-reporter/blob/master/src/analytics.js#L225-L229):

```javascript
if ((result.data.length > 0) && ("visitors" in result.data[0])) {
    result.totals.visitors = 0;
    for (var i=0; i<result.data.length; i++)
        result.totals.visitors += parseInt(result.data[i].visitors);
}
```

Note that it looks for the `visitors` prop in the results. The value for `visitors` is mapped from `ga:users` [here](https://github.com/18F/analytics-reporter/blob/master/src/analytics.js#L122), but is then overriden with the name `users` [here](https://github.com/18F/analytics-reporter/blob/master/src/analytics.js#L147).

I discovered this bug while writing tests for the code that processes the reports.

**Comment by konklone** [comment]
> I discovered this bug while writing tests for the code that processes the reports.

I am so glad you are doing this! :tada: for tests!
