### ISSUE TITLE
review how the report criteria are set up

### ISSUE THREAD

**Issue by gbinal** [18F/analytics-reporter#201]
@tdlowden and I were just looking at some of the settings in https://github.com/18F/analytics-reporter/blob/master/reports/usa.json and had some questions, e.g. for instance, for some of them, they have a `"start-date": "14daysAgo"` ([link](https://github.com/18F/analytics-reporter/blob/master/reports/usa.json#L362)) and but a description of `Participating hostnames over the last 30 days...` ([link](https://github.com/18F/analytics-reporter/blob/master/reports/usa.json#L369)).  

@jmhooper - We should schedule a session where the three of us go through these together and make sure we're on the same page about them and agree with their settings.  I'll reach out with a scheduler to that effect.

**Comment by konklone** [comment]
One thing you could do is just ditch the description. It's only used in the JSON itself as a convenience to those reading the JSON directly, but if keeping it manually up to date isn't working, then you could either

* drop the description field entirely
* generate it dynamically from the rest of the data

**Comment by gbinal** [comment]
Thanks, @konklone.  I don't feel the need to take those steps yet.  

Rather, I've started a PR (https://github.com/18F/analytics-reporter/pull/202) to make some mild edits.
