### ISSUE TITLE
Use `date` instead of `date_time` in Postgres

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics-reporter#226]
Currently we have a `date_time` attribute in the database and API response. This made sense when we had data that was described per hour, but does not make sense now that all of the data is broken up by day.

We should remove the time data from the `date_time` column in the database and use `date` instead.

**Comment by gbinal** [comment]
Makes sense to me.  👍

**Comment by ctrimm** [comment]
@jmhooper - Should this issue be closed out since it was merged in?
