### ISSUE TITLE
Publishing different formats requires querying for each format

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics-reporter#229]
As it stands, we need to query twice to publish reports with 2 different data types. For example, to publish a CSV and JSON report, we need to run and process 2 queries, one for each report, even though it is the same data.

We should look into a way to publish the results of a query in multiple formats so that we can query once and then publish twice.

**Comment by konklone** [comment]
Huge :+1:. Easy way to cut down our requests and save on processing time.

**Comment by levinmr** [comment]
moved to trello backlog

**Comment by levinmr** [comment]
This is complete now
