### ISSUE TITLE
avgSessionDuration "Units"

### ISSUE THREAD

**Issue by KiwiAJ** [18F/analytics-reporter#239]
Could someone provide the unit measure for the avgSessionDuration data element found throughout this tool? I was unable to find it in the documentation.

**Comment by tdlowden** [comment]
Hi @KiwiAJ, it's by seconds. You can also check the GA API documentation here:

https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=session&jump=ga_sessionduration
