### ISSUE TITLE
Visitors by agency, day and city

### ISSUE THREAD

**Issue by zhangchuck** [18F/analytics-reporter#248]
# Issue

Looking to be able to create a dataset of **visitors per city, by [agency/subagency/domain], by [day/week/month]** via the API.

The output would be similar to, but at an agency level and over time:

https://analytics.usa.gov/data/commerce/top-cities-realtime.json
#112 

Is this possible? If it's not currently possible, how would I go about adding this functionality?

**Comment by zhangchuck** [comment]
Would it just be adding `"ga:city"` to the line here:

https://github.com/18F/analytics-reporter/blob/1cf105cc8a0e34f1ba7cbd8a34d99a8260eea8ac/reports/reports.json#L48

**Comment by tdlowden** [comment]
Thanks for this suggestion! We'll take a look and see if it's feasible.
