### ISSUE TITLE
Unhandled rejection Error: No key or key file specified in config

### ISSUE THREAD

**Issue by tanakamapondera** [18F/analytics-reporter#269]
I have followed all the steps until creating an env file who all the appropriate environment variables. I have placed them in a ".env" in the root directory. Currently, I have Email, ID and  Key defined. 
However, when I run the code using the command "analytics" I keep getting the following error message: 
![error](https://user-images.githubusercontent.com/43476830/83423598-32a3c800-a3f9-11ea-960c-0c69225c6b3f.PNG)

Am I placing the ".env" file in the wrong location?
I tried this with both the NPM and Docker installations and both gave me the same error message. Apologies if this seems like such a trivial issue but Couldn't really find any other help online

**Comment by tdlowden** [comment]
thanks for the issue. @jmhooper or @ryanhofdotgov -- if you get a sec, could you 👁️ this?

**Comment by ryanhofdotgov** [comment]
@tanakamapondera The .env file is intended for use with the [autoenv tool](https://github.com/inishchith/autoenv), which will set project specific environment variables as you change from directory to directory using your shell program (bash, etc.).

Looks like you are using Git for Windows bash emulator? I don't have any experience with it, but if you aren't using `autoenv`, I would just try manually sourcing the `.env` file to set all the required variables you've configured in .env before running `analytics`:
```
$ source .env
$ analytics
```

**Comment by tanakamapondera** [comment]
@ryanhofdotgov Apologies for not getting back to you but this solution worked for me. This is still something that I'm looking into but I've currently put this on hold so I will close this issue out
