### ISSUE TITLE
Explore creating a machine user as a Google profile vs a Google group for authentiation

### ISSUE THREAD

**Issue by NoahKunin** [18F/analytics-reporter#27]
Look at after launch.

**Comment by konklone** [comment]
One thing I learned yesterday - projects can be shared across many users. So now @ramirezg and I are both owners of the auth'ed "project" under our GSA accounts. We could add you and any others as well.

**Comment by konklone** [comment]
@laurenancona accidental close?

**Comment by laurenancona** [comment]
Hmm, yes, unintentionally added to that milestone, too.

**Comment by konklone** [comment]
Though - @NoahKunin I kind of don't recall the impetus here. I believe the authentication is connected to one or more individual Google Apps accounts, managed in the Google Developer Console. Are we missing anything here?

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.

**Comment by levinmr** [comment]
done
