### ISSUE TITLE
CSV versions of the data

### ISSUE THREAD

**Issue by konklone** [18F/analytics-reporter#43]
A `--csv` flag that, once given the transformed JSON, runs them into a CSV version (and then publishes, writes, or prints them as it ordinarily would).

**Comment by ramirezg** [comment]
@konklone how far along you are you on this? If If it doesn't need to get done immediately, I wouldn't mind working on this.

**Comment by konklone** [comment]
Haven't started! If you want to tackle it, please do.

**Comment by konklone** [comment]
Fixed by #49.
