### ISSUE TITLE
Dependabot SPAM

### ISSUE THREAD

**Issue by abitrolly** [18F/analytics-reporter#624]
There are a lot of PRs that are autogenerated by @dependabot - https://github.com/18F/analytics-reporter/pulls

For people watching this repo, those PRs would generate a lot of notification that bear little value, as they don't seem to be related to security risks or can be acted on be outside contributors.

Maybe @dependabot had a mode to edit existing PRs and create them only if there are security threats.

**Comment by ryanwoldatwork** [comment]
Thanks @abitrolly,
Most of these PR's have been addressed.
