### ISSUE TITLE
Ditch cron for a lightweight alternative

### ISSUE THREAD

**Issue by konklone** [18F/analytics-reporter#65]
`cron` is an old, brittle piece of software. It also [can't do sub-minute tasks](http://stackoverflow.com/questions/1034243/how-to-get-a-unix-script-to-run-every-15-seconds/1034256#1034256).

All the "Node cron" libraries I've found are for running raw Node code at given intervals, not running unix commands. I'd like a simple, stable cron alternative.

**Comment by jmhooper** [comment]
We're no longer running cron now that we have an app deployed to cloud.gov
