### ISSUE TITLE
Can't access analytics sites anymore

### ISSUE THREAD

**Issue by abitrolly** [18F/analytics-reporter#669]
I've just noticed that none of the sites listed in description can be opened.

* https://analytics.usa.gov/

![image](https://user-images.githubusercontent.com/8781107/228462900-188e5cfa-65a4-42ad-99c7-b5976ad62f35.png)

* http://analytics.phila.gov/

![image](https://user-images.githubusercontent.com/8781107/228465780-dd1553f3-dc6d-4937-980b-5662241862c7.png)

* https://analytics.cityofsacramento.org/

![image](https://user-images.githubusercontent.com/8781107/228466332-c49b22eb-4cfb-41ac-a24d-b73f043dc02a.png)

**Comment by ryanwoldatwork** [comment]
hi @abitrolly - is this still occurring? I'm able to access these URLs

**Comment by abitrolly** [comment]
@ryanwoldatwork https://analytics.usa.gov/ works now.

http://analytics.phila.gov/ gives the same error - "having trouble finding" - immediately.

https://analytics.cityofsacramento.org - just hangs indefinitely.

**Comment by ryanwoldatwork** [comment]
Hi @abitrolly - it appears analytics.phila.gov is now [offline](https://github.com/CityOfPhiladelphia/analytics.phila.gov).

And, I am able to access Sacramento successfully.

I have also removed both sites URL's from this repository's description.

Please let me know if you have any follow-up questions. Otherwise, I'll close this issue in a few days.

**Comment by abitrolly** [comment]
https://cityofsacramento.org hangs for me as well. https://downforeveryoneorjustme.com/cityofsacramento.org?proto=https and https://downforeveryoneorjustme.com/analytics.cityofsacramento.org?proto=https reports both sites are down, so you probably have an exclusive access.

**Comment by abitrolly** [comment]
@ryanwoldatwork exclusive access is most likely for you location, and is not device specific. https://www.cityofsacramento.gov/ works ok though. So if there is no reporter installation, the ticket can be closed then.
