### ISSUE TITLE
Update documentation in  analytics-reporter repository README.md

### ISSUE THREAD

**Issue by nick-mon1** [18F/analytics-reporter#766]
## Background

Updates to `analytic-reporter` might require updates to the README.md file

## Acceptance Criteria

- [x] Any required changes that impact the README.md documentation during the UA -> GA4 upgrade should be updated

**Comment by scottqueen-bixal** [comment]
updated and moving upstream: https://github.com/18F/analytics-reporter/pull/769/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
