### ISSUE TITLE
See if we can isolate the IE technical preview

### ISSUE THREAD

**Issue by konklone** [18F/analytics-reporter#77]
We have to whitelist individual browsers and versions, so to keep on top of IE we'll want to proactively whitelist "12", "13", "14", etc. I think the Technical Preview will be "TP", but it's not unlikely we'll find an example already in the analytics.

**Comment by laurenancona** [comment]
Here's a [custom segment](https://www.google.com/analytics/web/template?uid=i0mLut7YRQ6KP277EG_OgQ) that isolates `user agent` for Microsoft Edge
AFAIK Microsoft isn't surfacing `browser` to prevent targeted workarounds à la IE.
For reference, the custom seg includes `Operating System Version` = `NT` and `Browser Version` = `42.0.2311.135`. [(source)](http://www.geekwire.com/2015/the-challenge-of-tracking-microsofts-new-edge-browser-in-google-analytics/)

**UPDATE:** As of last week (8/13), Google has added support for `Browser` = `Edge`, but so far I am not seeing traffic equal to that of a custom segment built around the [announced user agent](https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx#edge) of `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.<OS build number>`

**Comment by konklone** [comment]
@laurenancona Hmm. How many days of data are you comparing between Google's method and yours?

**Comment by laurenancona** [comment]
<img width="1013" alt="screen shot 2015-08-20 at 9 30 24 am" src="https://cloud.githubusercontent.com/assets/2152151/9384423/6b81d79e-471e-11e5-9d59-8119111248e1.png">
Interestingly, this appears to be resolving as of yesterday.

**Comment by konklone** [comment]
OK - given that, I'm inclined to rely on `Browser` = `Edge`, at least for our work. Do you think that's okay, or would you like to collect more data?

**Comment by laurenancona** [comment]
I think if nothing else, it's consistent with the way we're mapping other `Browser` data. I'd like to confirm with a few more days' data, but otherwise I'd be okay with using.

**Comment by konklone** [comment]
Cool. If you remember, please post the updated data here in a few days. Otherwise, we'll get to this eventually during our next round of work.

**Comment by laurenancona** [comment]
This is now fully supported via GA and was added to the dashboard in 3f5cd3871ee79885ad51bb556e66775106fd16d3
