### ISSUE TITLE
Reduce the frequency of realtime report API calls

### ISSUE THREAD

**Issue by levinmr** [18F/analytics-reporter#783]
## Background

Universal analytics provided realtime report updates every 5 minutes.  GA4 has changed the reporting update frequency to 30 minutes.  However, the analytics-reporter still makes API calls for realtime reports every 5 minutes.

## Acceptance Criteria

The analytics reporter makes less frequent API calls for realtime reports, while continuing to provide realtime data updates for the website every 30 minutes.

**Comment by p1kalys** [comment]
Hi @levinmr, I would like to work on this issue, please assign it to me.

**Comment by levinmr** [comment]
done
