### ISSUE TITLE
clarify environment variables in installation instructions

### ISSUE THREAD

**Issue by vlandham** [18F/analytics-reporter#82]
Really awesome tool. Thanks so much for getting it out and available. 

I would just suggest a tiny bit of clarification around the installation instructions. Specifically, I got stuck at two spots:

- the path `.pem` file apparently needs to be absolute? (which the path you provide hints to - i just didn't see it).
- I was unfamiliar with where to find `ANALYTICS_REPORT_IDS` - and originally had the ID of my account instead of my web-site. 

Maybe something along the lines of:

Set the following environment variables:

```bash
export ANALYTICS_REPORT_EMAIL="asdfghjkl@developer.gserviceaccount.com"
export ANALYTICS_REPORT_IDS="ga:XXXXXX"
export ANALYTICS_KEY_PATH="/path/to/secret_key.pem"
```

`ANALYTICS_REPORT_EMAIL` is the generated client email address from the API service account that you have granted read & analyze permissions to within Google Analytics for the View you want to extract data from.

`ANALYTICS_REPORT_IDS` is the Google Analytics ID for that View. You can find it in the Admin panel for your GA account under "View Settings". Prefix it with `ga:`to make it work.

`ANALYTICS_KEY_PATH` is the **absolute** path to the `.pem` file generated above.

----

Just a suggestion!

Also, you may consider outputting the full error message, when errors occur. That was useful for tracking down my problems.

Thanks again!

**Comment by markbosky** [comment]
Thank you @vlandham for explaining the ANALYTICS_REPORT_IDS. I was also having trouble myself figuring out what it was referring to.  

I am however, still cloudy on how to test my configuration via:
./bin/report users

Do I need to install a certain dependency for this functionality?

Running "analytics" gives me: "ERROR AFTER QUERYING: {"code":403}"

**Comment by vlandham** [comment]
@markbosky  - Ah. I was confused there as well. 
My guess is that their binary used to be called `report` and so if it was in your local directory, then this would how you would call it. 

I installed analytics-reporter in a local directory and then ran 
```
./node_modules/analytics-reporter/bin/analytics users
```
to get things to work. 

The error you are getting I saw when I had the wrong value for ANALYTICS_REPORT_IDS. I was using the account's id and not the website/view's id. 

I believe 403 indicates that the user doesn't have access (forbidden) for that content. 
For me - this was due to attempting to access the wrong ID. It might also be that the email address doesn't have read & analyze permissions?

**Comment by ahecht** [comment]
I had the 403 problem too - make sure you have the Analytics API enabled in your Google Developer Console, under APIs & Auth > APIs

**Comment by vlandham** [comment]
ahhh. thats it!
i did that, but i didn't know if that step was required or not.

**Comment by markbosky** [comment]
Thanks! That's exactly what fixed my 403 issue too @ahecht .  Everything seems to be up and running now.

**Comment by laurenancona** [comment]
Closed by `bd9c68`and a little help from some friends.
